eureka:
    client:
        service-url:
            defaultZone: http://localhost:9090/eureka
server:
    port: 0
spring:
    application:
        name: purchase-service
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: sa
        password: pass
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
    kafka:
        topic: purchase-topic
        admin:
            bootstrap-servers: localhost:9092
management:
    endpoints:
        web:
            exposure:
                include: "*"

