eureka:
    instance:
        hostname: Biswo.Dlink
        preferIpAddress: false
        ipAddress:
        nonSecurePort: ${server.port}
        instanceId: ${spring.application.name}:${server.port}
    client:
        service-url:
            defaultZone: http://localhost:9090/eureka
server:
    port: 0
spring:
    application:
        name: notification-service
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: sa
        password: pass
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
    kafka:
        topics:
            first: purchase-topic
            second: kafka-topic
            RETRY: purchase-topic.RETRY
            DLT: purchase-topic.DLT
        group_id: group_new
        bootstrap-servers: localhost:9092
        consumer:
            group-id: group_new
            key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
management:
    endpoints:
        web:
            exposure:
                include: "*"
