eureka:
    instance:
        hostname: Biswo.Dlink
        preferIpAddress: false
        ipAddress: 
        nonSecurePort: ${server.port}
        instanceId: ${spring.application.name}:${server.port}
    client:
        serviceUrl:
            defaultZone: http://localhost:9090/eureka
server:
    port: 9091
spring:
    application:
        name: my-api-gateway
    cloud:
        gateway:
            routes:
            -   predicates:
                - Path=/api/v1/digitalbooks/readers/**
                uri: lb://reader-service/
            -   predicates:
                - Path=/api/v1/digitalbooks/author/**
                uri: lb://author-service/
            - predicates:
              - Path=/api/v1/digitalbooks/purchase/**
              uri: lb://purchase-service/
            - predicates:
              - Path=/notification/**
              uri: lb://notification-service/

management:
    endpoints:
        web:
            exposure:
                include: "*"
